export enum NotificationType {
	DEBUG_NOTIFY_CLIENT_ADDED,
	DEBUG_NOTIFY_CLIENT_REMOVED,
	DEBUG_NOTIFY_CLIENT_SUBSCRIBED,
	DEBUG_NOTIFY_CLIENT_UNSUBSCRIBED,
	DEBUG_NOTIFY_KEY_LOCKED,
	DEBUG_NOTIFY_KEY_UNLOCKED,
}
export enum CommandType {
	APP_CMD_OBJECT_INIT_DATA,
	DEBUG_CMD_GET_KEY_LOCKER,
	DEBUG_CMD_GET_PROPS_PUBLISHER,
	DEBUG_CMD_GET_OBJS_PUBLISHER,
	DEBUG_CMD_GET_CLIENTS,
	DEBUG_CMD_GET_CLIENTS_SUBSCRIPTIONS,
	DEBUG_CMD_GET_SERVER_STATS,
	DEBUG_CMD_GET_SERVER_INFO,
	DEBUG_CMD_SET_LOG_LEVEL,
	DEBUG_CMD_SAVE_SNAPSHOT,
	DEBUG_CMD_LOAD_SNAPSHOT,
	DEBUG_CMD_EJECT_CLIENT,
	DEBUG_CMD_LOAD_PROPERTIES,
}
export enum PacketType {
	PS_CLIENT_INFO,
	APP_OBJECT_CREATE,
	APP_OBJECT_DELETE,		//deliberate delete by the client
	APP_PUBLISHED_OBJECTS,

	APP_PARAM_PUBLISH,
	APP_PARAM_RETRACT,    //deliberate delete by the client
	APP_PUBLISHED_PARAMS,

	APP_ENUM_PUBLISH,
	APP_ENUM_RETRACT,    //deliberate delete by the client
	APP_PUBLISHED_ENUMS,

	APP_PARAM_UPDATE,

	APP_PARAM_SUBSCRIBE,
	APP_PARAM_UNSUBSCRIBE,

	APP_PARAM_LOCK,
	APP_PARAM_UNLOCK,

	APP_REQUEST,
	APP_RESPONSE,

	APP_REGISTER_NOTIFICATIONS,
	APP_NOTIFICATIONS,

	APP_COMMAND,
	APP_DATA_FOR_REMOTE_APP
}